// src/app/unsubscribe/page.tsx
/**
 * Unsubscribe Page
 * 
 * Beautiful unsubscribe page matching the site's stunning design aesthetic.
 * 
 * @author John Chezik
 * @version 1.0.0
 * @created 2024
 */

'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Mail, CheckCircle, AlertCircle, ArrowLeft, Music, BookOpen, Camera, Calendar } from 'lucide-react';

function UnsubscribePageContent() {
  const searchParams = useSearchParams();
  const [email, setEmail] = useState('');
  const [token, setToken] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [status, setStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [message, setMessage] = useState('');
  const [reason, setReason] = useState('');

  useEffect(() => {
    const emailParam = searchParams.get('email');
    const tokenParam = searchParams.get('token');
    
    if (emailParam) setEmail(emailParam);
    if (tokenParam) setToken(tokenParam);
  }, [searchParams]);

  const handleUnsubscribe = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!email || !token) {
      setStatus('error');
      setMessage('Invalid unsubscribe link. Please contact support.');
      return;
    }

    setIsLoading(true);
    setStatus('idle');

    try {
      const response = await fetch('/api/email/unsubscribe', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email,
          token,
          reason: reason || 'user_requested'
        })
      });

      const result = await response.json();

      if (response.ok && result.success) {
        setStatus('success');
        setMessage(result.message);
      } else {
        setStatus('error');
        setMessage(result.error?.message || 'Failed to unsubscribe. Please try again.');
      }
    } catch (error) {
      console.error('Unsubscribe error:', error);
      setStatus('error');
      setMessage('Something went wrong. Please try again or contact support.');
    } finally {
      setIsLoading(false);
    }
  };

  // Always render the same structure to avoid hydration mismatch

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      {/* Animated Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_#111111_0%,_#000000_70%)]"></div>
        
        {/* Floating Orbs */}
        <div className="absolute top-20 left-10 w-64 h-64 bg-gradient-to-r from-blue-500/20 to-purple-600/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-10 w-48 h-48 bg-gradient-to-r from-pink-500/20 to-red-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-32 h-32 bg-gradient-to-r from-green-500/20 to-teal-500/20 rounded-full blur-3xl animate-pulse delay-2000"></div>
      </div>

      {/* Navigation */}
      <nav className="relative z-10 p-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold bg-gradient-to-r from-white to-blue-400 bg-clip-text text-transparent hover:scale-105 transition-transform">
            John Chezik
          </Link>
          <Link 
            href="/" 
            className="flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-lg border border-white/20 rounded-lg hover:bg-white/20 transition-all duration-200"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Main Content */}
      <div className="relative z-10 container mx-auto px-6 py-16">
        <div className="max-w-2xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-24 h-24 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full mb-8 relative">
              <Mail className="w-12 h-12 text-white" />
              <div className="absolute inset-0 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full blur-xl opacity-50 animate-pulse"></div>
            </div>
            
            <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-white via-blue-100 to-purple-200 bg-clip-text text-transparent">
              Unsubscribe
            </h1>
            <p className="text-xl text-gray-300 max-w-md mx-auto leading-relaxed">
              We&apos;re sorry to see you go, but we completely understand. 
              You can always resubscribe anytime.
            </p>
          </div>

          {/* Status Messages */}
          {status === 'success' && (
            <div className="mb-8 p-6 bg-green-500/10 border border-green-500/30 rounded-2xl backdrop-blur-lg">
              <div className="flex items-center gap-3">
                <CheckCircle className="w-6 h-6 text-green-400 flex-shrink-0" />
                <div>
                  <h3 className="text-green-400 font-semibold mb-1">Successfully Unsubscribed</h3>
                  <p className="text-green-200 text-sm">{message}</p>
                </div>
              </div>
            </div>
          )}

          {status === 'error' && (
            <div className="mb-8 p-6 bg-red-500/10 border border-red-500/30 rounded-2xl backdrop-blur-lg">
              <div className="flex items-center gap-3">
                <AlertCircle className="w-6 h-6 text-red-400 flex-shrink-0" />
                <div>
                  <h3 className="text-red-400 font-semibold mb-1">Error</h3>
                  <p className="text-red-200 text-sm">{message}</p>
                </div>
              </div>
            </div>
          )}

          {/* Form Card */}
          <div className="bg-white/5 backdrop-blur-xl rounded-3xl p-8 border border-white/10 shadow-2xl">
            <form onSubmit={handleUnsubscribe} className="space-y-6">
              {/* Email Field */}
              <div>
                <label htmlFor="email" className="block text-sm font-medium text-gray-300 mb-3">
                  Email Address
                </label>
                <div className="relative">
                  <input
                    type="email"
                    id="email"
                    value={email}
                    onChange={(e) => setEmail(e.target.value)}
                    className="w-full px-4 py-4 bg-white/5 border border-white/20 rounded-xl text-white placeholder-gray-400 focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500/50 transition-all duration-200 backdrop-blur-sm"
                    placeholder="your.email@example.com"
                    required
                    disabled={isLoading}
                  />
                  <Mail className="absolute right-4 top-1/2 transform -translate-y-1/2 w-5 h-5 text-gray-400" />
                </div>
              </div>

              {/* Reason Field */}
              <div>
                <label htmlFor="reason" className="block text-sm font-medium text-gray-300 mb-3">
                  Reason for unsubscribing (optional)
                </label>
                <select
                  id="reason"
                  value={reason}
                  onChange={(e) => setReason(e.target.value)}
                  className="w-full px-4 py-4 bg-white/5 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500/50 transition-all duration-200 backdrop-blur-sm appearance-none cursor-pointer"
                  disabled={isLoading}
                >
                  <option value="" className="bg-gray-800">Select a reason...</option>
                  <option value="too_frequent" className="bg-gray-800">Emails too frequent</option>
                  <option value="not_relevant" className="bg-gray-800">Content not relevant</option>
                  <option value="too_many_emails" className="bg-gray-800">Too many emails</option>
                  <option value="never_signed_up" className="bg-gray-800">Never signed up</option>
                  <option value="other" className="bg-gray-800">Other</option>
                </select>
              </div>

              {/* Warning Notice */}
              <div className="bg-amber-500/10 border border-amber-500/30 rounded-xl p-6 backdrop-blur-sm">
                <div className="flex items-start gap-3">
                  <AlertCircle className="w-5 h-5 text-amber-400 flex-shrink-0 mt-0.5" />
                  <div>
                    <h4 className="text-amber-400 font-semibold mb-2">Important Notice</h4>
                    <p className="text-amber-200 text-sm leading-relaxed">
                      Unsubscribing will stop all newsletter emails from John Chezik, including updates about new albums, books, and exclusive content. You can resubscribe anytime on our website.
                    </p>
                  </div>
                </div>
              </div>

              {/* Submit Button */}
              <button
                type="submit"
                disabled={isLoading || !email}
                className="w-full px-8 py-4 bg-gradient-to-r from-red-500 to-red-600 text-white rounded-xl hover:from-red-600 hover:to-red-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 font-semibold text-lg shadow-lg hover:shadow-red-500/25 hover:-translate-y-0.5"
              >
                {isLoading ? (
                  <div className="flex items-center justify-center gap-3">
                    <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                    Processing...
                  </div>
                ) : (
                  'Unsubscribe from Newsletter'
                )}
              </button>
            </form>
          </div>

          {/* What You'll Miss */}
          <div className="mt-12 text-center">
            <h3 className="text-xl font-semibold text-gray-300 mb-6">What you&apos;ll miss:</h3>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4 max-w-lg mx-auto">
              <div className="flex items-center gap-3 p-4 bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl">
                <Music className="w-5 h-5 text-blue-400" />
                <span className="text-gray-300 text-sm">New album releases</span>
              </div>
              <div className="flex items-center gap-3 p-4 bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl">
                <BookOpen className="w-5 h-5 text-green-400" />
                <span className="text-gray-300 text-sm">Book updates</span>
              </div>
              <div className="flex items-center gap-3 p-4 bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl">
                <Camera className="w-5 h-5 text-purple-400" />
                <span className="text-gray-300 text-sm">Studio sessions</span>
              </div>
              <div className="flex items-center gap-3 p-4 bg-white/5 backdrop-blur-sm border border-white/10 rounded-xl">
                <Calendar className="w-5 h-5 text-orange-400" />
                <span className="text-gray-300 text-sm">Live events</span>
              </div>
            </div>
          </div>

          {/* Contact Info */}
          <div className="text-center mt-12">
            <p className="text-gray-400 text-sm">
              Questions? Contact us at{' '}
              <a 
                href="mailto:media@chezik.eu" 
                className="text-blue-400 hover:text-blue-300 transition-colors duration-200 font-medium"
              >
                media@chezik.eu
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function UnsubscribePage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="text-white text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-white mx-auto mb-4"></div>
          <p>Loading...</p>
        </div>
      </div>
    }>
      <UnsubscribePageContent />
    </Suspense>
  );
}

// src/routes/unsubscribe/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { Mail, CheckCircle, ArrowLeft, Heart } from 'lucide-svelte';
	import type { PageData } from './$types';
	
	export let data: PageData;
	
	let mounted = false;
	let email = data.email;
	let token = data.token;
	let isUnsubscribing = false;
	let unsubscribeStatus: 'idle' | 'success' | 'error' = 'idle';
	let message = '';
	
	onMount(() => {
		mounted = true;
	});
	
	async function handleUnsubscribe() {
		if (!email || isUnsubscribing) return;
		
		isUnsubscribing = true;
		unsubscribeStatus = 'idle';
		
		try {
			const response = await fetch('/api/unsubscribe', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ email, token })
			});
			
			const result = await response.json();
			
			if (response.ok) {
				unsubscribeStatus = 'success';
				message = result.message;
			} else {
				unsubscribeStatus = 'error';
				message = result.error || 'Something went wrong. Please try again.';
			}
		} catch (error) {
			console.error('Unsubscribe error:', error);
			unsubscribeStatus = 'error';
			message = 'Something went wrong. Please try again.';
		} finally {
			isUnsubscribing = false;
		}
	}
</script>

<svelte:head>
	<title>Unsubscribe - John Chezik</title>
	<meta name="description" content="Unsubscribe from John Chezik's newsletter" />
</svelte:head>

<div class="unsubscribe-page">
	<div class="container">
		<!-- Header -->
		<div class="page-header" class:mounted>
			<div class="header-icon">
				<Mail size={32} />
			</div>
			<h1 class="page-title">Newsletter Unsubscribe</h1>
			<p class="page-description">
				We're sorry to see you go! You can unsubscribe from John Chezik's newsletter below.
			</p>
		</div>
		
		<!-- Main Content -->
		<div class="content-section" class:mounted>
			{#if unsubscribeStatus === 'success'}
				<!-- Success State -->
				<div class="success-card">
					<div class="success-icon">
						<CheckCircle size={48} />
					</div>
					<h2 class="success-title">You've been unsubscribed</h2>
					<p class="success-message">
						{message}
					</p>
					<div class="success-details">
						<p><strong>Email:</strong> {email}</p>
						<p><strong>Date:</strong> {new Date().toLocaleDateString()}</p>
					</div>
					<div class="success-actions">
						<a href="/" class="btn btn-primary">
							<ArrowLeft size={18} />
							Back to Website
						</a>
						<button 
							class="btn btn-secondary"
							on:click={() => {
								unsubscribeStatus = 'idle';
								message = '';
							}}
						>
							Resubscribe
						</button>
					</div>
				</div>
			{:else if unsubscribeStatus === 'error'}
				<!-- Error State -->
				<div class="error-card">
					<div class="error-icon">
						<Mail size={48} />
					</div>
					<h2 class="error-title">Something went wrong</h2>
					<p class="error-message">{message}</p>
					<div class="error-actions">
						<button 
							class="btn btn-primary"
							on:click={() => {
								unsubscribeStatus = 'idle';
								message = '';
							}}
						>
							Try Again
						</button>
						<a href="/" class="btn btn-secondary">
							Back to Website
						</a>
					</div>
				</div>
			{:else}
				<!-- Unsubscribe Form -->
				<div class="unsubscribe-card">
					<div class="card-header">
						<h2 class="card-title">Confirm Unsubscribe</h2>
						<p class="card-description">
							Are you sure you want to unsubscribe from John Chezik's newsletter? 
							You'll miss out on exclusive updates about new albums, books, and behind-the-scenes content.
						</p>
					</div>
					
					<div class="email-display">
						<div class="email-icon">
							<Mail size={20} />
						</div>
						<span class="email-text">{email || 'No email provided'}</span>
					</div>
					
					<div class="what-youll-miss">
						<h3 class="miss-title">What you'll miss:</h3>
						<div class="miss-features">
							<div class="feature">
								<span class="feature-icon">🎵</span>
								<span>New album releases & previews</span>
							</div>
							<div class="feature">
								<span class="feature-icon">📚</span>
								<span>Book updates & exclusive content</span>
							</div>
							<div class="feature">
								<span class="feature-icon">🎸</span>
								<span>Behind-the-scenes studio sessions</span>
							</div>
							<div class="feature">
								<span class="feature-icon">🎤</span>
								<span>Live events & concert announcements</span>
							</div>
						</div>
					</div>
					
					<div class="unsubscribe-actions">
						<button
							class="btn btn-primary btn-large"
							on:click={handleUnsubscribe}
							disabled={isUnsubscribing || !email}
						>
							{#if isUnsubscribing}
								<div class="spinner"></div>
								Unsubscribing...
							{:else}
								<Mail size={18} />
								Yes, Unsubscribe Me
							{/if}
						</button>
						
						<a href="/" class="btn btn-secondary btn-large">
							<ArrowLeft size={18} />
							Keep My Subscription
						</a>
					</div>
					
					<div class="alternative-option">
						<p class="alternative-text">
							Don't want to unsubscribe completely? 
							<a href="/preferences?email={email}" class="alternative-link">
								Adjust your email preferences instead
							</a>
						</p>
					</div>
				</div>
			{/if}
		</div>
		
		<!-- Footer -->
		<div class="page-footer" class:mounted>
			<div class="footer-content">
				<div class="footer-icon">
					<Heart size={20} />
				</div>
				<p class="footer-text">
					Thank you for being part of John Chezik's community. 
					You're always welcome back!
				</p>
			</div>
		</div>
	</div>
</div>

<style>
	.unsubscribe-page {
		min-height: 100vh;
		background: linear-gradient(180deg, #000000 0%, #0f0f0f 50%, #000000 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		padding: var(--space-lg);
		position: relative;
	}
	
	.unsubscribe-page::before {
		content: '';
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		height: 1px;
		background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
	}
	
	.container {
		width: 100%;
		max-width: 600px;
		margin: 0 auto;
	}
	
	.page-header {
		text-align: center;
		margin-bottom: var(--space-4xl);
		opacity: 0;
		transform: translateY(30px);
		transition: all 0.8s ease-out;
	}
	
	.page-header.mounted {
		opacity: 1;
		transform: translateY(0);
	}
	
	.header-icon {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 64px;
		height: 64px;
		background: var(--color-accent-primary);
		color: white;
		border-radius: 50%;
		margin-bottom: var(--space-lg);
	}
	
	.page-title {
		font-size: var(--text-4xl);
		font-weight: 800;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
		background: linear-gradient(135deg, #ffffff, #a0a0a0);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}
	
	.page-description {
		font-size: var(--text-lg);
		color: var(--color-text-secondary);
		line-height: 1.6;
	}
	
	.content-section {
		opacity: 0;
		transition: opacity 1s ease-out 0.3s;
	}
	
	.content-section.mounted {
		opacity: 1;
	}
	
	.unsubscribe-card,
	.success-card,
	.error-card {
		background: var(--glass-bg);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-xl);
		padding: var(--space-2xl);
		backdrop-filter: blur(20px);
		-webkit-backdrop-filter: blur(20px);
		text-align: center;
	}
	
	.card-header {
		margin-bottom: var(--space-xl);
	}
	
	.card-title {
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
	}
	
	.card-description {
		font-size: var(--text-base);
		color: var(--color-text-secondary);
		line-height: 1.6;
	}
	
	.email-display {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--space-sm);
		padding: var(--space-md);
		background: var(--color-bg-secondary);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-md);
		margin-bottom: var(--space-xl);
	}
	
	.email-icon {
		color: var(--color-accent-primary);
	}
	
	.email-text {
		font-weight: 600;
		color: var(--color-text-primary);
	}
	
	.what-youll-miss {
		margin-bottom: var(--space-xl);
		text-align: left;
	}
	
	.miss-title {
		font-size: var(--text-lg);
		font-weight: 600;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
		text-align: center;
	}
	
	.miss-features {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: var(--space-md);
	}
	
	.feature {
		display: flex;
		align-items: center;
		gap: var(--space-sm);
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
	}
	
	.feature-icon {
		font-size: var(--text-base);
	}
	
	.unsubscribe-actions {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
		margin-bottom: var(--space-lg);
	}
	
	.btn-large {
		width: 100%;
		padding: var(--space-md) var(--space-lg);
		font-size: var(--text-lg);
		font-weight: 600;
		gap: var(--space-sm);
	}
	
	.alternative-option {
		padding-top: var(--space-lg);
		border-top: 1px solid var(--glass-border);
	}
	
	.alternative-text {
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
		margin: 0;
	}
	
	.alternative-link {
		color: var(--color-accent-primary);
		text-decoration: none;
		font-weight: 500;
	}
	
	.alternative-link:hover {
		text-decoration: underline;
	}
	
	.success-card {
		text-align: center;
	}
	
	.success-icon {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 80px;
		height: 80px;
		background: rgba(48, 209, 88, 0.1);
		color: #30d158;
		border-radius: 50%;
		margin-bottom: var(--space-lg);
	}
	
	.success-title {
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
	}
	
	.success-message {
		font-size: var(--text-base);
		color: var(--color-text-secondary);
		line-height: 1.6;
		margin-bottom: var(--space-lg);
	}
	
	.success-details {
		background: var(--color-bg-secondary);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-md);
		padding: var(--space-md);
		margin-bottom: var(--space-lg);
		text-align: left;
	}
	
	.success-details p {
		margin: 0 0 var(--space-xs) 0;
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
	}
	
	.success-details p:last-child {
		margin-bottom: 0;
	}
	
	.success-actions {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}
	
	.error-card {
		text-align: center;
	}
	
	.error-icon {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 80px;
		height: 80px;
		background: rgba(255, 69, 58, 0.1);
		color: #ff453a;
		border-radius: 50%;
		margin-bottom: var(--space-lg);
	}
	
	.error-title {
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
	}
	
	.error-message {
		font-size: var(--text-base);
		color: var(--color-text-secondary);
		line-height: 1.6;
		margin-bottom: var(--space-lg);
	}
	
	.error-actions {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}
	
	.spinner {
		width: 18px;
		height: 18px;
		border: 2px solid rgba(255, 255, 255, 0.3);
		border-top: 2px solid white;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}
	
	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}
	
	.page-footer {
		text-align: center;
		margin-top: var(--space-4xl);
		opacity: 0;
		transition: opacity 1s ease-out 0.6s;
	}
	
	.page-footer.mounted {
		opacity: 1;
	}
	
	.footer-content {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--space-sm);
		padding: var(--space-lg);
		background: var(--glass-bg);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-lg);
		backdrop-filter: blur(20px);
		-webkit-backdrop-filter: blur(20px);
	}
	
	.footer-icon {
		color: var(--color-accent-primary);
	}
	
	.footer-text {
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
		margin: 0;
	}
	
	@media (max-width: 640px) {
		.unsubscribe-page {
			padding: var(--space-md);
		}
		
		.page-title {
			font-size: var(--text-3xl);
		}
		
		.miss-features {
			grid-template-columns: 1fr;
		}
		
		.unsubscribe-card,
		.success-card,
		.error-card {
			padding: var(--space-xl);
		}
	}
</style>
