// src/components/Navigation.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { Menu, X, Search } from 'lucide-svelte';
	import ThemeToggle from './ThemeToggle.svelte';
	import SearchModal from './SearchModal.svelte';
	
	let isScrolled = false;
	let isMobileMenuOpen = false;
	let showSearchModal = false;
	
	const navItems = [
		{ href: '#home', label: 'Home' },
		{ href: '#albums', label: 'Albums' },
		{ href: '#books', label: 'Books' },
		{ href: '#blog', label: 'Blog' },
		{ href: '#about', label: 'About' },
		{ href: '#contact', label: 'Contact' }
	];
	
	onMount(() => {
		const handleScroll = () => {
			isScrolled = window.scrollY > 50;
		};
		
		window.addEventListener('scroll', handleScroll);
		return () => window.removeEventListener('scroll', handleScroll);
	});
	
	function toggleMobileMenu() {
		isMobileMenuOpen = !isMobileMenuOpen;
	}
	
	function closeMobileMenu() {
		isMobileMenuOpen = false;
	}
	
	function handleNavClick(href: string) {
		closeMobileMenu();
		
		// Smooth scroll to section
		const element = document.querySelector(href);
		if (element) {
			element.scrollIntoView({ behavior: 'smooth' });
		}
	}
	
	function openSearch() {
		showSearchModal = true;
	}
	
	function handleSearchNavigate(event: CustomEvent) {
		const section = event.detail;
		const element = document.querySelector(section);
		if (element) {
			element.scrollIntoView({ behavior: 'smooth' });
		}
		showSearchModal = false;
	}
	
	// Handle keyboard shortcut for search
	function handleKeydown(event: KeyboardEvent) {
		if ((event.metaKey || event.ctrlKey) && event.key === 'k') {
			event.preventDefault();
			openSearch();
		}
	}
</script>

<svelte:window on:keydown={handleKeydown} />

<nav class="navigation" class:scrolled={isScrolled}>
	<div class="container">
		<div class="nav-content">
			<!-- Logo -->
			<div class="logo">
				<a href="#home" on:click|preventDefault={() => handleNavClick('#home')}>
					<span class="logo-text">John Chezik</span>
				</a>
			</div>
			
			<!-- Desktop Navigation -->
			<div class="nav-right">
				<ul class="nav-links desktop-nav">
					{#each navItems as item}
						<li>
							<a 
								href={item.href} 
								on:click|preventDefault={() => handleNavClick(item.href)}
								class="nav-link"
							>
								{item.label}
							</a>
						</li>
					{/each}
				</ul>
				
				<button 
					class="search-button"
					on:click={openSearch}
					aria-label="Search (⌘K)"
					title="Search (⌘K)"
				>
					<Search size={18} />
				</button>
				
				<ThemeToggle />
			</div>
			
			<!-- Mobile Menu Button -->
			<button 
				class="mobile-menu-btn"
				on:click={toggleMobileMenu}
				aria-label="Toggle mobile menu"
			>
				{#if isMobileMenuOpen}
					<X size={24} />
				{:else}
					<Menu size={24} />
				{/if}
			</button>
		</div>
	</div>
	
	<!-- Mobile Navigation -->
	{#if isMobileMenuOpen}
		<div class="mobile-nav" class:open={isMobileMenuOpen}>
			<ul class="mobile-nav-links">
				{#each navItems as item}
					<li>
						<a 
							href={item.href} 
							on:click|preventDefault={() => handleNavClick(item.href)}
							class="mobile-nav-link"
						>
							{item.label}
						</a>
					</li>
				{/each}
			</ul>
		</div>
	{/if}
</nav>

<SearchModal 
	bind:isOpen={showSearchModal} 
	on:navigate={handleSearchNavigate}
	on:close={() => showSearchModal = false}
/>

<style>
	.navigation {
		position: fixed;
		top: 0;
		left: 0;
		right: 0;
		z-index: 1000;
		padding: var(--space-md) 0;
		transition: all var(--transition-normal);
		background: transparent;
	}
	
	.navigation.scrolled {
		background: rgba(0, 0, 0, 0.8);
		backdrop-filter: blur(20px);
		-webkit-backdrop-filter: blur(20px);
		border-bottom: 1px solid rgba(255, 255, 255, 0.1);
		padding: var(--space-sm) 0;
	}
	
	.nav-content {
		display: flex;
		align-items: center;
		justify-content: space-between;
	}
	
	.logo {
		z-index: 1001;
	}
	
	.logo a {
		text-decoration: none;
		color: var(--color-text-primary);
	}
	
	.logo-text {
		font-size: var(--text-xl);
		font-weight: 700;
		background: linear-gradient(135deg, #ffffff, #007aff);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}
	
	.nav-right {
		display: flex;
		align-items: center;
		gap: var(--space-lg);
	}
	
	.desktop-nav {
		display: flex;
		list-style: none;
		gap: var(--space-xl);
		margin: 0;
		padding: 0;
	}
	
	.nav-link {
		color: var(--color-text-secondary);
		text-decoration: none;
		font-weight: 500;
		font-size: var(--text-base);
		transition: all var(--transition-normal);
		position: relative;
		padding: var(--space-sm) 0;
	}
	
	.nav-link::after {
		content: '';
		position: absolute;
		bottom: 0;
		left: 0;
		width: 0;
		height: 2px;
		background: var(--color-accent-primary);
		transition: width var(--transition-normal);
	}
	
	.nav-link:hover {
		color: var(--color-text-primary);
	}
	
	.nav-link:hover::after {
		width: 100%;
	}
	
	.search-button {
		background: none;
		border: none;
		color: var(--color-text-secondary);
		cursor: pointer;
		padding: var(--space-sm);
		border-radius: var(--radius-md);
		transition: all var(--transition-normal);
		display: flex;
		align-items: center;
		justify-content: center;
	}
	
	.search-button:hover {
		background: var(--glass-bg);
		color: var(--color-text-primary);
	}
	
	.mobile-menu-btn {
		display: none;
		background: none;
		border: none;
		color: var(--color-text-primary);
		cursor: pointer;
		padding: var(--space-sm);
		border-radius: var(--radius-md);
		transition: all var(--transition-normal);
		z-index: 1001;
	}
	
	.mobile-menu-btn:hover {
		background: var(--glass-bg);
	}
	
	.mobile-nav {
		position: absolute;
		top: 100%;
		left: 0;
		right: 0;
		background: rgba(0, 0, 0, 0.95);
		backdrop-filter: blur(20px);
		-webkit-backdrop-filter: blur(20px);
		border-bottom: 1px solid rgba(255, 255, 255, 0.1);
		opacity: 0;
		transform: translateY(-20px);
		transition: all var(--transition-normal);
		pointer-events: none;
	}
	
	.mobile-nav.open {
		opacity: 1;
		transform: translateY(0);
		pointer-events: all;
	}
	
	.mobile-nav-links {
		list-style: none;
		margin: 0;
		padding: var(--space-lg) 0;
	}
	
	.mobile-nav-link {
		display: block;
		color: var(--color-text-primary);
		text-decoration: none;
		font-weight: 500;
		font-size: var(--text-lg);
		padding: var(--space-md) var(--space-lg);
		transition: all var(--transition-normal);
		border-left: 3px solid transparent;
	}
	
	.mobile-nav-link:hover {
		background: var(--glass-bg);
		border-left-color: var(--color-accent-primary);
		color: var(--color-accent-primary);
	}
	
	@media (max-width: 768px) {
		.nav-right {
			display: none;
		}
		
		.mobile-menu-btn {
			display: flex;
			align-items: center;
			justify-content: center;
		}
	}
</style>

// src/components/Navigation.tsx
/**
 * Advanced Navigation Component for Next.js v15
 * 
 * Production-ready navigation with glass morphism, search modal,
 * theme toggle, and your exact original beautiful design.
 * Built for Vercel deployment with advanced features.
 * 
 * @author John Chezik
 * @version 1.0.0
 * @created 2024
 */

'use client';

import React, { useEffect, useState, useCallback } from 'react';
import { Menu, X, Search, Sun } from 'lucide-react';
import EnterpriseSearchModal from './EnterpriseSearchModal';

interface NavItem {
  href: string;
  label: string;
}

interface SearchResult {
  type: 'album' | 'book' | 'blog' | 'section' | 'gallery';
  title: string;
  description: string;
  href: string;
  anchorId?: string;
  category?: string;
  location?: string;
  year?: string;
  genre?: string;
  tags?: string[];
}

const Navigation: React.FC = () => {
  const [isScrolled, setIsScrolled] = useState(false);
  const [isMobileMenuOpen, setIsMobileMenuOpen] = useState(false);
  const [showSearchModal, setShowSearchModal] = useState(false);
  const [theme, setTheme] = useState<'dark' | 'light'>('dark');
  const [mounted, setMounted] = useState(false);

  const navItems: NavItem[] = [
    { href: '#home', label: 'Home' },
    { href: '#albums', label: 'Albums' },
    { href: '#books', label: 'Books' },
    { href: '#blog', label: 'Blog' },
    { href: '#gallery', label: 'Gallery' },
    { href: '#about', label: 'About' },
    { href: '#contact', label: 'Contact' }
  ];

  // Initialize theme and scroll listener
  useEffect(() => {
    setMounted(true);
    
    // Load saved theme only on client
    if (typeof window !== 'undefined') {
      const savedTheme = localStorage.getItem('theme') as 'dark' | 'light' || 'dark';
      setTheme(savedTheme);
      document.documentElement.setAttribute('data-theme', savedTheme);
      // Remove all theme classes and add the new one
      const baseClasses = document.body.className.replace(/theme-\w+/g, '').trim();
      document.body.className = baseClasses + ` theme-${savedTheme}`;
    }

    // Scroll listener
    const handleScroll = () => {
      setIsScrolled(window.scrollY > 50);
    };
    
    // Set initial scroll state only on client
    if (typeof window !== 'undefined') {
      handleScroll();
      window.addEventListener('scroll', handleScroll);
    }
    
    return () => {
      if (typeof window !== 'undefined') {
        window.removeEventListener('scroll', handleScroll);
      }
    };
  }, []);

  const closeSearch = useCallback(() => {
    setShowSearchModal(false);
  }, []);

  const openSearch = useCallback(() => {
    setShowSearchModal(true);
  }, []);

  // Keyboard shortcut for search (Cmd/Ctrl + K)
  useEffect(() => {
    const handleKeydown = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key === 'k') {
        event.preventDefault();
        openSearch();
      }
      
      // Close search with Escape
      if (event.key === 'Escape' && showSearchModal) {
        closeSearch();
      }
    };

    window.addEventListener('keydown', handleKeydown);
    return () => window.removeEventListener('keydown', handleKeydown);
  }, [showSearchModal, closeSearch, openSearch]);

  const toggleMobileMenu = useCallback(() => {
    setIsMobileMenuOpen(!isMobileMenuOpen);
  }, [isMobileMenuOpen]);

  const closeMobileMenu = useCallback(() => {
    setIsMobileMenuOpen(false);
  }, []);

  const handleNavClick = useCallback((href: string) => {
    closeMobileMenu();
    
    // Smooth scroll to section
    const element = document.querySelector(href);
    if (element) {
      element.scrollIntoView({ behavior: 'smooth' });
    }
  }, [closeMobileMenu]);

  const toggleTheme = useCallback(() => {
    const newTheme = theme === 'dark' ? 'light' : 'dark';
    setTheme(newTheme);
    document.documentElement.setAttribute('data-theme', newTheme);
    // Remove all theme classes and add the new one
    const baseClasses = document.body.className.replace(/theme-\w+/g, '').trim();
    document.body.className = baseClasses + ` theme-${newTheme}`;
    localStorage.setItem('theme', newTheme);
  }, [theme]);

  const handleSearchResultClick = useCallback((result: SearchResult) => {
    // First navigate to the section
    handleNavClick(result.href);
    
    // If there's a specific anchor ID, scroll to it after a short delay
    if (result.anchorId) {
      setTimeout(() => {
        const element = document.getElementById(result.anchorId!);
        if (element) {
          element.scrollIntoView({ 
            behavior: 'smooth', 
            block: 'center' 
          });
          
          // Add a temporary highlight effect
          element.style.transition = 'background-color 0.3s ease';
          element.style.backgroundColor = 'rgba(59, 130, 246, 0.1)';
          setTimeout(() => {
            element.style.backgroundColor = '';
          }, 2000);
        }
      }, 300);
    }
    
    // If it's a gallery result, trigger a custom event to filter the gallery
    if (result.type === 'gallery' && result.category) {
      // Dispatch a custom event to filter the gallery
      const filterEvent = new CustomEvent('galleryFilter', {
        detail: { category: result.category, title: result.title }
      });
      window.dispatchEvent(filterEvent);
    }
    
    closeSearch();
  }, [handleNavClick, closeSearch]);

  // Prevent hydration mismatch by not rendering until mounted
  if (!mounted) {
    return (
      <nav className="navigation" role="navigation" aria-label="Main navigation">
        <div className="container">
          <div className="nav-content">
            <div className="logo">
              <a href="#home" aria-label="John Chezik - Go to homepage">
                <span className="logo-text">John Chezik</span>
              </a>
            </div>
            <div className="nav-right">
              <ul className="nav-links desktop-nav" role="menubar">
                {navItems.map((item) => (
                  <li key={item.href} role="none">
                    <a 
                      href={item.href} 
                      className="nav-link"
                      role="menuitem"
                      aria-label={`Navigate to ${item.label} section`}
                    >
                      {item.label}
                    </a>
                  </li>
                ))}
              </ul>
              <button className="search-button" aria-label="Search (⌘K)" title="Search (⌘K)">
                <Search size={20} />
              </button>
              <button 
                className="theme-toggle" 
                aria-label="Toggle theme" 
                title="Toggle theme"
                onClick={toggleTheme}
              >
                <Sun size={20} />
              </button>
            </div>
            <button className="mobile-menu-button" aria-label="Toggle mobile menu">
              <Menu size={24} />
            </button>
          </div>
          
          {/* Mobile Menu - always present but hidden */}
          <div 
            className="mobile-menu"
            role="dialog"
            aria-modal="true"
            aria-label="Mobile navigation menu"
            aria-hidden="true"
          >
            <div className="mobile-menu-content">
              <ul className="mobile-nav-links" role="menubar">
                {navItems.map((item) => (
                  <li key={item.href} role="none">
                    <a
                      href={item.href}
                      className="mobile-nav-link"
                      role="menuitem"
                      aria-label={`Navigate to ${item.label} section`}
                    >
                      {item.label}
                    </a>
                  </li>
                ))}
              </ul>
              
              <div className="mobile-actions">
                <button className="mobile-action-btn">
                  <Search size={20} />
                  Search
                </button>
                
                <button className="mobile-action-btn">
                  <Sun size={20} />
                  Light Theme
                </button>
              </div>
            </div>
          </div>
        </div>
      </nav>
    );
  }

  return (
    <>
      <nav 
        className={`navigation ${isScrolled ? 'scrolled' : ''}`}
        role="navigation"
        aria-label="Main navigation"
        suppressHydrationWarning
      >
        <div className="container">
          <div className="nav-content">
            {/* Logo */}
            <div className="logo">
              <a 
                href="#home" 
                onClick={(e) => { e.preventDefault(); handleNavClick('#home'); }}
                aria-label="John Chezik - Go to homepage"
              >
                <span className="logo-text">John Chezik</span>
              </a>
            </div>
            
            {/* Desktop Navigation */}
            <div className="nav-right">
              <ul className="nav-links desktop-nav" role="menubar">
                {navItems.map((item) => (
                  <li key={item.href} role="none">
                    <a 
                      href={item.href} 
                      onClick={(e) => { e.preventDefault(); handleNavClick(item.href); }}
                      className="nav-link"
                      role="menuitem"
                      aria-label={`Navigate to ${item.label} section`}
                    >
                      {item.label}
                    </a>
                  </li>
                ))}
              </ul>
              
              <button 
                className="search-button"
                onClick={openSearch}
                aria-label="Search (⌘K)"
                title="Search (⌘K)"
              >
                <Search size={20} />
              </button>
              
              <button 
                className="theme-toggle"
                onClick={toggleTheme}
                aria-label="Toggle theme"
                title="Toggle theme"
                suppressHydrationWarning
              >
                <Sun size={20} />
              </button>
            </div>

            {/* Mobile Menu Button */}
            <button 
              className="mobile-menu-button"
              onClick={toggleMobileMenu}
              aria-label="Toggle mobile menu"
              suppressHydrationWarning
            >
              {isMobileMenuOpen ? <X size={24} /> : <Menu size={24} />}
            </button>
          </div>

          {/* Mobile Menu */}
          <div 
            className={`mobile-menu ${isMobileMenuOpen ? 'open' : ''}`}
            role="dialog"
            aria-modal="true"
            aria-label="Mobile navigation menu"
            aria-hidden={!isMobileMenuOpen}
            suppressHydrationWarning
          >
            <div className="mobile-menu-content">
              <ul className="mobile-nav-links" role="menubar">
                {navItems.map((item) => (
                  <li key={item.href} role="none">
                    <a
                      href={item.href}
                      onClick={(e) => { e.preventDefault(); handleNavClick(item.href); }}
                      className="mobile-nav-link"
                      role="menuitem"
                      aria-label={`Navigate to ${item.label} section`}
                    >
                      {item.label}
                    </a>
                  </li>
                ))}
              </ul>
              
              <div className="mobile-actions">
                <button 
                  className="mobile-action-btn"
                  onClick={openSearch}
                >
                  <Search size={20} />
                  Search
                </button>
                
                <button 
                  className="mobile-action-btn"
                  onClick={toggleTheme}
                  suppressHydrationWarning
                >
                  <Sun size={20} />
                  Light Theme
                </button>
              </div>
            </div>
          </div>
        </div>
      </nav>

      {/* Enterprise Search Modal */}
      <EnterpriseSearchModal
        isOpen={showSearchModal}
        onClose={closeSearch}
        onResultClick={handleSearchResultClick}
      />
    </>
  );
};

export default Navigation;
