// src/app/preferences/page.tsx
/**
 * Email Preferences Page
 * 
 * Beautiful email preferences page matching the site's stunning design aesthetic.
 * 
 * @author John Chezik
 * @version 1.0.0
 * @created 2024
 */

'use client';

import React, { useState, useEffect, useCallback, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { Settings, CheckCircle, AlertCircle, ArrowLeft, Save, Mail, Music, BookOpen, Camera, Calendar, FileText, Star, ShoppingBag, Users, Clock, Globe, Monitor } from 'lucide-react';

interface EmailPreferences {
  frequency: string;
  content_types: {
    albums: boolean;
    books: boolean;
    studio_updates: boolean;
    events: boolean;
    blog_posts: boolean;
    exclusive_content: boolean;
    merchandise: boolean;
    collaborations: boolean;
  };
  timezone: string;
  language: string;
  digest_format: string;
  unsubscribe_all: boolean;
}

function PreferencesPageContent() {
  const searchParams = useSearchParams();
  const [email, setEmail] = useState('');
  const [token, setToken] = useState('');
  const [isLoading, setIsLoading] = useState(false);
  const [isSaving, setIsSaving] = useState(false);
  const [status, setStatus] = useState<'idle' | 'success' | 'error'>('idle');
  const [message, setMessage] = useState('');
  
  const [preferences, setPreferences] = useState<EmailPreferences>({
    frequency: 'weekly',
    content_types: {
      albums: true,
      books: true,
      studio_updates: true,
      events: true,
      blog_posts: true,
      exclusive_content: true,
      merchandise: false,
      collaborations: true,
    },
    timezone: 'America/New_York',
    language: 'en',
    digest_format: 'html',
    unsubscribe_all: false,
  });

  const loadPreferences = useCallback(async () => {
    setIsLoading(true);
    try {
      const response = await fetch(`/api/email/preferences?email=${encodeURIComponent(email)}&token=${encodeURIComponent(token)}`);
      const result = await response.json();
      
      if (response.ok && result.success) {
        setPreferences(result.preferences || preferences);
      } else {
        setStatus('error');
        setMessage(result.error?.message || 'Failed to load preferences.');
      }
    } catch (error) {
      console.error('Load preferences error:', error);
      setStatus('error');
      setMessage('Failed to load preferences. Please try again.');
    } finally {
      setIsLoading(false);
    }
  }, [email, token, preferences]);

  useEffect(() => {
    const emailParam = searchParams.get('email');
    const tokenParam = searchParams.get('token');
    
    if (emailParam) setEmail(emailParam);
    if (tokenParam) setToken(tokenParam);
    
    // Load preferences if we have valid params
    if (emailParam && tokenParam) {
      loadPreferences();
    }
  }, [searchParams, loadPreferences]);

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    
    if (!email || !token) {
      setStatus('error');
      setMessage('Invalid preferences link. Please contact support.');
      return;
    }

    setIsSaving(true);
    setStatus('idle');

    try {
      const response = await fetch('/api/email/preferences', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          email,
          token,
          preferences
        })
      });

      const result = await response.json();

      if (response.ok && result.success) {
        setStatus('success');
        setMessage(result.message || 'Preferences saved successfully!');
      } else {
        setStatus('error');
        setMessage(result.error?.message || 'Failed to save preferences. Please try again.');
      }
    } catch (error) {
      console.error('Save preferences error:', error);
      setStatus('error');
      setMessage('Something went wrong. Please try again or contact support.');
    } finally {
      setIsSaving(false);
    }
  };

  const updateContentType = (type: keyof EmailPreferences['content_types'], value: boolean) => {
    setPreferences(prev => ({
      ...prev,
      content_types: {
        ...prev.content_types,
        [type]: value
      }
    }));
  };

  const contentTypes = [
    { key: 'albums', label: 'New Albums', icon: Music, color: 'text-blue-400' },
    { key: 'books', label: 'Book Updates', icon: BookOpen, color: 'text-green-400' },
    { key: 'studio_updates', label: 'Studio Sessions', icon: Camera, color: 'text-purple-400' },
    { key: 'events', label: 'Live Events', icon: Calendar, color: 'text-orange-400' },
    { key: 'blog_posts', label: 'Blog Posts', icon: FileText, color: 'text-indigo-400' },
    { key: 'exclusive_content', label: 'Exclusive Content', icon: Star, color: 'text-yellow-400' },
    { key: 'merchandise', label: 'Merchandise', icon: ShoppingBag, color: 'text-pink-400' },
    { key: 'collaborations', label: 'Collaborations', icon: Users, color: 'text-teal-400' },
  ];

  // Always render the same structure to avoid hydration mismatch

  return (
    <div className="min-h-screen bg-black text-white relative overflow-hidden">
      {/* Animated Background */}
      <div className="absolute inset-0 bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900">
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,_#111111_0%,_#000000_70%)]"></div>
        
        {/* Floating Orbs */}
        <div className="absolute top-20 left-10 w-64 h-64 bg-gradient-to-r from-blue-500/20 to-purple-600/20 rounded-full blur-3xl animate-pulse"></div>
        <div className="absolute bottom-20 right-10 w-48 h-48 bg-gradient-to-r from-pink-500/20 to-red-500/20 rounded-full blur-3xl animate-pulse delay-1000"></div>
        <div className="absolute top-1/2 left-1/2 transform -translate-x-1/2 -translate-y-1/2 w-32 h-32 bg-gradient-to-r from-green-500/20 to-teal-500/20 rounded-full blur-3xl animate-pulse delay-2000"></div>
      </div>

      {/* Navigation */}
      <nav className="relative z-10 p-6">
        <div className="container mx-auto flex items-center justify-between">
          <Link href="/" className="text-2xl font-bold bg-gradient-to-r from-white to-blue-400 bg-clip-text text-transparent hover:scale-105 transition-transform">
            John Chezik
          </Link>
          <Link 
            href="/" 
            className="flex items-center gap-2 px-4 py-2 bg-white/10 backdrop-blur-lg border border-white/20 rounded-lg hover:bg-white/20 transition-all duration-200"
          >
            <ArrowLeft className="w-4 h-4" />
            Back to Home
          </Link>
        </div>
      </nav>

      {/* Main Content */}
      <div className="relative z-10 container mx-auto px-6 py-16">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <div className="text-center mb-12">
            <div className="inline-flex items-center justify-center w-24 h-24 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full mb-8 relative">
              <Settings className="w-12 h-12 text-white" />
              <div className="absolute inset-0 bg-gradient-to-r from-blue-500 to-purple-600 rounded-full blur-xl opacity-50 animate-pulse"></div>
            </div>
            
            <h1 className="text-5xl font-bold mb-6 bg-gradient-to-r from-white via-blue-100 to-purple-200 bg-clip-text text-transparent">
              Email Preferences
            </h1>
            <p className="text-xl text-gray-300 max-w-md mx-auto leading-relaxed">
              Customize your email experience and stay connected with what matters most to you.
            </p>
          </div>

          {/* Status Messages */}
          {status === 'success' && (
            <div className="mb-8 p-6 bg-green-500/10 border border-green-500/30 rounded-2xl backdrop-blur-lg">
              <div className="flex items-center gap-3">
                <CheckCircle className="w-6 h-6 text-green-400 flex-shrink-0" />
                <div>
                  <h3 className="text-green-400 font-semibold mb-1">Preferences Saved</h3>
                  <p className="text-green-200 text-sm">{message}</p>
                </div>
              </div>
            </div>
          )}

          {status === 'error' && (
            <div className="mb-8 p-6 bg-red-500/10 border border-red-500/30 rounded-2xl backdrop-blur-lg">
              <div className="flex items-center gap-3">
                <AlertCircle className="w-6 h-6 text-red-400 flex-shrink-0" />
                <div>
                  <h3 className="text-red-400 font-semibold mb-1">Error</h3>
                  <p className="text-red-200 text-sm">{message}</p>
                </div>
              </div>
            </div>
          )}

          {/* Preferences Form */}
          <div className="bg-white/5 backdrop-blur-xl rounded-3xl p-8 border border-white/10 shadow-2xl">
            <form onSubmit={handleSave} className="space-y-8">
              {/* Email Frequency */}
              <div>
                <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
                  <Clock className="w-5 h-5 text-blue-400" />
                  Email Frequency
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {[
                    { value: 'daily', label: 'Daily', desc: 'Get updates every day' },
                    { value: 'weekly', label: 'Weekly', desc: 'Weekly digest (recommended)' },
                    { value: 'monthly', label: 'Monthly', desc: 'Monthly summary' },
                    { value: 'major_only', label: 'Major Updates Only', desc: 'Only important announcements' },
                  ].map((option) => (
                    <label key={option.value} className="flex items-center p-4 bg-white/5 border border-white/20 rounded-xl cursor-pointer hover:bg-white/10 transition-all duration-200">
                      <input
                        type="radio"
                        name="frequency"
                        value={option.value}
                        checked={preferences.frequency === option.value}
                        onChange={(e) => setPreferences(prev => ({ ...prev, frequency: e.target.value }))}
                        className="sr-only"
                      />
                      <div className={`w-4 h-4 rounded-full border-2 mr-3 flex items-center justify-center ${
                        preferences.frequency === option.value 
                          ? 'border-blue-500 bg-blue-500' 
                          : 'border-gray-400'
                      }`}>
                        {preferences.frequency === option.value && (
                          <div className="w-2 h-2 bg-white rounded-full"></div>
                        )}
                      </div>
                      <div>
                        <div className="text-white font-medium">{option.label}</div>
                        <div className="text-gray-400 text-sm">{option.desc}</div>
                      </div>
                    </label>
                  ))}
                </div>
              </div>

              {/* Content Types */}
              <div>
                <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
                  <Mail className="w-5 h-5 text-green-400" />
                  Content Types
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  {contentTypes.map(({ key, label, icon: Icon, color }) => (
                    <label key={key} className="flex items-center p-4 bg-white/5 border border-white/20 rounded-xl cursor-pointer hover:bg-white/10 transition-all duration-200">
                      <input
                        type="checkbox"
                        checked={preferences.content_types[key as keyof EmailPreferences['content_types']]}
                        onChange={(e) => updateContentType(key as keyof EmailPreferences['content_types'], e.target.checked)}
                        className="sr-only"
                      />
                      <div className={`w-5 h-5 rounded border-2 mr-3 flex items-center justify-center ${
                        preferences.content_types[key as keyof EmailPreferences['content_types']]
                          ? 'border-blue-500 bg-blue-500' 
                          : 'border-gray-400'
                      }`}>
                        {preferences.content_types[key as keyof EmailPreferences['content_types']] && (
                          <CheckCircle className="w-3 h-3 text-white" />
                        )}
                      </div>
                      <Icon className={`w-5 h-5 mr-3 ${color}`} />
                      <span className="text-white font-medium">{label}</span>
                    </label>
                  ))}
                </div>
              </div>

              {/* Email Format */}
              <div>
                <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
                  <Monitor className="w-5 h-5 text-purple-400" />
                  Email Format
                </h3>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {[
                    { value: 'html', label: 'HTML', desc: 'Rich formatting' },
                    { value: 'text', label: 'Text Only', desc: 'Simple text' },
                    { value: 'both', label: 'Both', desc: 'HTML with text fallback' },
                  ].map((option) => (
                    <label key={option.value} className="flex items-center p-4 bg-white/5 border border-white/20 rounded-xl cursor-pointer hover:bg-white/10 transition-all duration-200">
                      <input
                        type="radio"
                        name="digest_format"
                        value={option.value}
                        checked={preferences.digest_format === option.value}
                        onChange={(e) => setPreferences(prev => ({ ...prev, digest_format: e.target.value }))}
                        className="sr-only"
                      />
                      <div className={`w-4 h-4 rounded-full border-2 mr-3 flex items-center justify-center ${
                        preferences.digest_format === option.value 
                          ? 'border-blue-500 bg-blue-500' 
                          : 'border-gray-400'
                      }`}>
                        {preferences.digest_format === option.value && (
                          <div className="w-2 h-2 bg-white rounded-full"></div>
                        )}
                      </div>
                      <div>
                        <div className="text-white font-medium">{option.label}</div>
                        <div className="text-gray-400 text-sm">{option.desc}</div>
                      </div>
                    </label>
                  ))}
                </div>
              </div>

              {/* Timezone */}
              <div>
                <h3 className="text-xl font-semibold text-white mb-4 flex items-center gap-3">
                  <Globe className="w-5 h-5 text-orange-400" />
                  Timezone
                </h3>
                <select
                  value={preferences.timezone}
                  onChange={(e) => setPreferences(prev => ({ ...prev, timezone: e.target.value }))}
                  className="w-full px-4 py-4 bg-white/5 border border-white/20 rounded-xl text-white focus:outline-none focus:ring-2 focus:ring-blue-500/50 focus:border-blue-500/50 transition-all duration-200 backdrop-blur-sm appearance-none cursor-pointer"
                >
                  <option value="America/New_York" className="bg-gray-800">Eastern Time (ET)</option>
                  <option value="America/Chicago" className="bg-gray-800">Central Time (CT)</option>
                  <option value="America/Denver" className="bg-gray-800">Mountain Time (MT)</option>
                  <option value="America/Los_Angeles" className="bg-gray-800">Pacific Time (PT)</option>
                  <option value="Europe/London" className="bg-gray-800">London (GMT)</option>
                  <option value="Europe/Paris" className="bg-gray-800">Paris (CET)</option>
                  <option value="Asia/Tokyo" className="bg-gray-800">Tokyo (JST)</option>
                  <option value="Australia/Sydney" className="bg-gray-800">Sydney (AEST)</option>
                </select>
              </div>

              {/* Save Button */}
              <div className="pt-6 border-t border-white/10">
                <button
                  type="submit"
                  disabled={isSaving || isLoading}
                  className="w-full px-8 py-4 bg-gradient-to-r from-blue-500 to-purple-600 text-white rounded-xl hover:from-blue-600 hover:to-purple-700 disabled:opacity-50 disabled:cursor-not-allowed transition-all duration-200 font-semibold text-lg shadow-lg hover:shadow-blue-500/25 hover:-translate-y-0.5"
                >
                  {isSaving ? (
                    <div className="flex items-center justify-center gap-3">
                      <div className="w-5 h-5 border-2 border-white/30 border-t-white rounded-full animate-spin"></div>
                      Saving Preferences...
                    </div>
                  ) : (
                    <div className="flex items-center justify-center gap-3">
                      <Save className="w-5 h-5" />
                      Save Preferences
                    </div>
                  )}
                </button>
              </div>
            </form>
          </div>

          {/* Contact Info */}
          <div className="text-center mt-12">
            <p className="text-gray-400 text-sm">
              Need help? Contact us at{' '}
              <a 
                href="mailto:media@chezik.eu" 
                className="text-blue-400 hover:text-blue-300 transition-colors duration-200 font-medium"
              >
                media@chezik.eu
              </a>
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}

export default function PreferencesPage() {
  return (
    <Suspense fallback={
      <div className="min-h-screen bg-gradient-to-br from-slate-900 via-purple-900 to-slate-900 flex items-center justify-center">
        <div className="text-white text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-white mx-auto mb-4"></div>
          <p>Loading preferences...</p>
        </div>
      </div>
    }>
      <PreferencesPageContent />
    </Suspense>
  );
}

// src/routes/preferences/+page.svelte
<script lang="ts">
	import { onMount } from 'svelte';
	import { page } from '$app/stores';
	import { Settings, Mail, CheckCircle, ArrowLeft, Save, Music, BookOpen, Camera, Calendar } from 'lucide-svelte';
	import type { PageData } from './$types';
	
	export let data: PageData;
	
	let mounted = false;
	let email = data.email;
	let token = data.token;
	let isSaving = false;
	let saveStatus: 'idle' | 'success' | 'error' = 'idle';
	let message = '';
	
	// Preferences state
	let preferences = {
		frequency: 'weekly',
		contentTypes: {
			albums: true,
			books: true,
			studio: true,
			events: true
		},
		emailAddress: data.email
	};
	
	onMount(() => {
		mounted = true;
		// Load existing preferences if available (only if email and token are provided)
		if (email && token) {
			loadPreferences();
		}
	});
	
	async function loadPreferences() {
		if (!email) return;
		
		try {
			const response = await fetch(`/api/preferences?email=${encodeURIComponent(email)}&token=${encodeURIComponent(token)}`);
			if (response.ok) {
				const data = await response.json();
				preferences = { ...preferences, ...data.preferences };
			}
		} catch (error) {
			console.error('Error loading preferences:', error);
		}
	}
	
	async function handleSave() {
		if (!email || isSaving) return;
		
		isSaving = true;
		saveStatus = 'idle';
		
		try {
			const response = await fetch('/api/preferences', {
				method: 'POST',
				headers: {
					'Content-Type': 'application/json',
				},
				body: JSON.stringify({ 
					email,
					token,
					preferences 
				})
			});
			
			const result = await response.json();
			
			if (response.ok) {
				saveStatus = 'success';
				message = result.message;
			} else {
				saveStatus = 'error';
				message = result.error || 'Something went wrong. Please try again.';
			}
		} catch (error) {
			console.error('Save preferences error:', error);
			saveStatus = 'error';
			message = 'Something went wrong. Please try again.';
		} finally {
			isSaving = false;
		}
	}
	
	function toggleContentType(type: keyof typeof preferences.contentTypes) {
		preferences.contentTypes[type] = !preferences.contentTypes[type];
	}
</script>

<svelte:head>
	<title>Email Preferences - John Chezik</title>
	<meta name="description" content="Manage your email preferences for John Chezik's newsletter" />
</svelte:head>

<div class="preferences-page">
	<div class="container">
		<!-- Header -->
		<div class="page-header" class:mounted>
			<div class="header-icon">
				<Settings size={32} />
			</div>
			<h1 class="page-title">Email Preferences</h1>
			<p class="page-description">
				Customize your newsletter experience. Choose what content you want to receive and how often.
			</p>
		</div>
		
		<!-- Main Content -->
		<div class="content-section" class:mounted>
			{#if saveStatus === 'success'}
				<!-- Success State -->
				<div class="success-card">
					<div class="success-icon">
						<CheckCircle size={48} />
					</div>
					<h2 class="success-title">Preferences Updated</h2>
					<p class="success-message">
						{message}
					</p>
					<div class="success-actions">
						<button 
							class="btn btn-primary"
							on:click={() => {
								saveStatus = 'idle';
								message = '';
							}}
						>
							Continue Editing
						</button>
						<a href="/" class="btn btn-secondary">
							<ArrowLeft size={18} />
							Back to Website
						</a>
					</div>
				</div>
			{:else if saveStatus === 'error'}
				<!-- Error State -->
				<div class="error-card">
					<div class="error-icon">
						<Settings size={48} />
					</div>
					<h2 class="error-title">Something went wrong</h2>
					<p class="error-message">{message}</p>
					<div class="error-actions">
						<button 
							class="btn btn-primary"
							on:click={() => {
								saveStatus = 'idle';
								message = '';
							}}
						>
							Try Again
						</button>
						<a href="/" class="btn btn-secondary">
							Back to Website
						</a>
					</div>
				</div>
			{:else}
				<!-- Preferences Form -->
				<div class="preferences-card">
					<div class="card-header">
						<h2 class="card-title">Manage Your Subscription</h2>
						<p class="card-description">
							Personalize your newsletter experience by choosing your preferences below.
						</p>
					</div>
					
					<div class="email-display">
						<div class="email-icon">
							<Mail size={20} />
						</div>
						<span class="email-text">{email || 'No email provided'}</span>
					</div>
					
					<form on:submit|preventDefault={handleSave} class="preferences-form">
						<!-- Email Frequency -->
						<div class="preference-group">
							<h3 class="group-title">
								<Mail size={20} />
								Email Frequency
							</h3>
							<p class="group-description">
								How often would you like to receive emails?
							</p>
							<div class="frequency-options">
								<label class="frequency-option">
									<input
										type="radio"
										bind:group={preferences.frequency}
										value="weekly"
										class="frequency-input"
									/>
									<div class="option-content">
										<div class="option-title">Weekly</div>
										<div class="option-description">Get updates every week</div>
									</div>
								</label>
								
								<label class="frequency-option">
									<input
										type="radio"
										bind:group={preferences.frequency}
										value="monthly"
										class="frequency-input"
									/>
									<div class="option-content">
										<div class="option-title">Monthly</div>
										<div class="option-description">Get updates once a month</div>
									</div>
								</label>
								
								<label class="frequency-option">
									<input
										type="radio"
										bind:group={preferences.frequency}
										value="major"
										class="frequency-input"
									/>
									<div class="option-content">
										<div class="option-title">Major Updates Only</div>
										<div class="option-description">Only for new albums and books</div>
									</div>
								</label>
							</div>
						</div>
						
						<!-- Content Types -->
						<div class="preference-group">
							<h3 class="group-title">
								<Settings size={20} />
								Content Types
							</h3>
							<p class="group-description">
								Choose what type of content you want to receive:
							</p>
							<div class="content-options">
								<label class="content-option">
									<input
										type="checkbox"
										bind:checked={preferences.contentTypes.albums}
										class="content-input"
									/>
									<div class="option-icon">
										<Music size={20} />
									</div>
									<div class="option-content">
										<div class="option-title">New Album Releases</div>
										<div class="option-description">Exclusive previews and behind-the-scenes content</div>
									</div>
								</label>
								
								<label class="content-option">
									<input
										type="checkbox"
										bind:checked={preferences.contentTypes.books}
										class="content-input"
									/>
									<div class="option-icon">
										<BookOpen size={20} />
									</div>
									<div class="option-content">
										<div class="option-title">Book Updates</div>
										<div class="option-description">Early access to new chapters and insights</div>
									</div>
								</label>
								
								<label class="content-option">
									<input
										type="checkbox"
										bind:checked={preferences.contentTypes.studio}
										class="content-input"
									/>
									<div class="option-icon">
										<Camera size={20} />
									</div>
									<div class="option-content">
										<div class="option-title">Studio Sessions</div>
										<div class="option-description">Behind-the-scenes footage and stories</div>
									</div>
								</label>
								
								<label class="content-option">
									<input
										type="checkbox"
										bind:checked={preferences.contentTypes.events}
										class="content-input"
									/>
									<div class="option-icon">
										<Calendar size={20} />
									</div>
									<div class="option-content">
										<div class="option-title">Live Events</div>
										<div class="option-description">Concert dates, book signings, and meetups</div>
									</div>
								</label>
							</div>
						</div>
						
						<!-- Save Actions -->
						<div class="save-actions">
							<button
								type="submit"
								class="btn btn-primary btn-large"
								disabled={isSaving}
							>
								{#if isSaving}
									<div class="spinner"></div>
									Saving...
								{:else}
									<Save size={18} />
									Save Preferences
								{/if}
							</button>
							
							<a href="/" class="btn btn-secondary btn-large">
								<ArrowLeft size={18} />
								Back to Website
							</a>
						</div>
					</form>
					
					<div class="unsubscribe-option">
						<p class="unsubscribe-text">
							Want to unsubscribe completely? 
							<a href="/unsubscribe?email={email}" class="unsubscribe-link">
								Click here to unsubscribe
							</a>
						</p>
					</div>
				</div>
			{/if}
		</div>
	</div>
</div>

<style>
	.preferences-page {
		min-height: 100vh;
		background: linear-gradient(180deg, #000000 0%, #0f0f0f 50%, #000000 100%);
		display: flex;
		align-items: center;
		justify-content: center;
		padding: var(--space-lg);
		position: relative;
	}
	
	.preferences-page::before {
		content: '';
		position: absolute;
		top: 0;
		left: 0;
		right: 0;
		height: 1px;
		background: linear-gradient(90deg, transparent, rgba(255, 255, 255, 0.1), transparent);
	}
	
	.container {
		width: 100%;
		max-width: 700px;
		margin: 0 auto;
	}
	
	.page-header {
		text-align: center;
		margin-bottom: var(--space-4xl);
		opacity: 0;
		transform: translateY(30px);
		transition: all 0.8s ease-out;
	}
	
	.page-header.mounted {
		opacity: 1;
		transform: translateY(0);
	}
	
	.header-icon {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 64px;
		height: 64px;
		background: var(--color-accent-primary);
		color: white;
		border-radius: 50%;
		margin-bottom: var(--space-lg);
	}
	
	.page-title {
		font-size: var(--text-4xl);
		font-weight: 800;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
		background: linear-gradient(135deg, #ffffff, #a0a0a0);
		-webkit-background-clip: text;
		-webkit-text-fill-color: transparent;
		background-clip: text;
	}
	
	.page-description {
		font-size: var(--text-lg);
		color: var(--color-text-secondary);
		line-height: 1.6;
	}
	
	.content-section {
		opacity: 0;
		transition: opacity 1s ease-out 0.3s;
	}
	
	.content-section.mounted {
		opacity: 1;
	}
	
	.preferences-card,
	.success-card,
	.error-card {
		background: var(--glass-bg);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-xl);
		padding: var(--space-2xl);
		backdrop-filter: blur(20px);
		-webkit-backdrop-filter: blur(20px);
	}
	
	.card-header {
		text-align: center;
		margin-bottom: var(--space-xl);
	}
	
	.card-title {
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
	}
	
	.card-description {
		font-size: var(--text-base);
		color: var(--color-text-secondary);
		line-height: 1.6;
	}
	
	.email-display {
		display: flex;
		align-items: center;
		justify-content: center;
		gap: var(--space-sm);
		padding: var(--space-md);
		background: var(--color-bg-secondary);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-md);
		margin-bottom: var(--space-xl);
	}
	
	.email-icon {
		color: var(--color-accent-primary);
	}
	
	.email-text {
		font-weight: 600;
		color: var(--color-text-primary);
	}
	
	.preferences-form {
		display: flex;
		flex-direction: column;
		gap: var(--space-2xl);
	}
	
	.preference-group {
		background: var(--color-bg-secondary);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-lg);
		padding: var(--space-xl);
	}
	
	.group-title {
		display: flex;
		align-items: center;
		gap: var(--space-sm);
		font-size: var(--text-xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-sm);
	}
	
	.group-description {
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
		margin-bottom: var(--space-lg);
		line-height: 1.5;
	}
	
	.frequency-options {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}
	
	.frequency-option {
		display: flex;
		align-items: center;
		gap: var(--space-md);
		padding: var(--space-lg);
		background: var(--glass-bg);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-md);
		cursor: pointer;
		transition: all var(--transition-normal);
	}
	
	.frequency-option:hover {
		border-color: var(--color-accent-primary);
		background: var(--color-bg-elevated);
	}
	
	.frequency-input {
		width: 20px;
		height: 20px;
		accent-color: var(--color-accent-primary);
	}
	
	.option-content {
		flex: 1;
	}
	
	.option-title {
		font-size: var(--text-base);
		font-weight: 600;
		color: var(--color-text-primary);
		margin-bottom: var(--space-xs);
	}
	
	.option-description {
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
	}
	
	.content-options {
		display: grid;
		grid-template-columns: 1fr 1fr;
		gap: var(--space-md);
	}
	
	.content-option {
		display: flex;
		align-items: flex-start;
		gap: var(--space-md);
		padding: var(--space-lg);
		background: var(--glass-bg);
		border: 1px solid var(--glass-border);
		border-radius: var(--radius-md);
		cursor: pointer;
		transition: all var(--transition-normal);
	}
	
	.content-option:hover {
		border-color: var(--color-accent-primary);
		background: var(--color-bg-elevated);
	}
	
	.content-input {
		width: 20px;
		height: 20px;
		accent-color: var(--color-accent-primary);
		margin-top: 2px;
	}
	
	.option-icon {
		color: var(--color-accent-primary);
		flex-shrink: 0;
	}
	
	.save-actions {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
		margin-top: var(--space-lg);
	}
	
	.btn-large {
		width: 100%;
		padding: var(--space-md) var(--space-lg);
		font-size: var(--text-lg);
		font-weight: 600;
		gap: var(--space-sm);
	}
	
	.unsubscribe-option {
		padding-top: var(--space-lg);
		border-top: 1px solid var(--glass-border);
		text-align: center;
		margin-top: var(--space-lg);
	}
	
	.unsubscribe-text {
		font-size: var(--text-sm);
		color: var(--color-text-secondary);
		margin: 0;
	}
	
	.unsubscribe-link {
		color: var(--color-accent-primary);
		text-decoration: none;
		font-weight: 500;
	}
	
	.unsubscribe-link:hover {
		text-decoration: underline;
	}
	
	.success-card,
	.error-card {
		text-align: center;
	}
	
	.success-icon {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 80px;
		height: 80px;
		background: rgba(48, 209, 88, 0.1);
		color: #30d158;
		border-radius: 50%;
		margin-bottom: var(--space-lg);
	}
	
	.success-title {
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
	}
	
	.success-message {
		font-size: var(--text-base);
		color: var(--color-text-secondary);
		line-height: 1.6;
		margin-bottom: var(--space-lg);
	}
	
	.success-actions {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}
	
	.error-icon {
		display: inline-flex;
		align-items: center;
		justify-content: center;
		width: 80px;
		height: 80px;
		background: rgba(255, 69, 58, 0.1);
		color: #ff453a;
		border-radius: 50%;
		margin-bottom: var(--space-lg);
	}
	
	.error-title {
		font-size: var(--text-2xl);
		font-weight: 700;
		color: var(--color-text-primary);
		margin-bottom: var(--space-md);
	}
	
	.error-message {
		font-size: var(--text-base);
		color: var(--color-text-secondary);
		line-height: 1.6;
		margin-bottom: var(--space-lg);
	}
	
	.error-actions {
		display: flex;
		flex-direction: column;
		gap: var(--space-md);
	}
	
	.spinner {
		width: 18px;
		height: 18px;
		border: 2px solid rgba(255, 255, 255, 0.3);
		border-top: 2px solid white;
		border-radius: 50%;
		animation: spin 1s linear infinite;
	}
	
	@keyframes spin {
		0% { transform: rotate(0deg); }
		100% { transform: rotate(360deg); }
	}
	
	@media (max-width: 768px) {
		.content-options {
			grid-template-columns: 1fr;
		}
		
		.preferences-page {
			padding: var(--space-md);
		}
		
		.page-title {
			font-size: var(--text-3xl);
		}
		
		.preferences-card,
		.success-card,
		.error-card {
			padding: var(--space-xl);
		}
	}
</style>
